version: '3.7'

services:
  fastapi_app:
    container_name: fastapi_app
    image: fastapi_app
    build: 
      context: .
    networks:
      - fastapi_net
    depends_on:
      fastapi_db:
        condition: service_healthy
    ports:
    - "8000:8000"

  fastapi_db:
    container_name: fastapi_db
    image: postgres:14
    networks:
      - fastapi_net
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 2s
      timeout: 5s
      retries: 10

networks:
  fastapi_net: